using Sandbox;
using Sandbox.Diagnostics;
using Sandbox.Utility.BBox2D;
using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Net.Security;
using System.Runtime.InteropServices;
using static Sandbox.PhysicsContact;



public sealed class ChunkPoint : Component
{
	/// <summary>
	/// Gives a specific list of chunks for this ChunkPoint. This behavior will determine whether or not it is a whitelist of chunks or a blacklist via IsWhitelist. If it is empty, nothing happens.
	/// </summary>
	/// 
	[Property] PrefabFile[] SpecificChunkList { get; set; }

	/// <summary>
	/// Whether or not specific chunk list is a whitelist or blacklist.
	/// </summary>
	/// 
	[Property] bool IsWhitelist { get; set; } = true;

	/// <summary>
	/// The chunk we have generated. Will be null if a chunk is not generated by us yet.
	/// </summary>
	/// 

	public GameObject GeneratedChunk;

	/// <summary>
	/// The Chunk Prefab we have selected. This is then used to generate our chunk we are responsible for when the time comes. (e.g. the player is closer to us.)
	/// </summary>
	/// 

	public PrefabFile SelectedChunkPrefab;

	private StageMain StageMain;

	private ChunkSystem ChunkSystem;

	private Random ChunkRandom;

	private FastTimer ChunkProcUpdateTick = FastTimer.StartNew();

	/// <summary>
	/// A loop flag that indicates the current player that is being examined by this ChunkPoint.
	/// </summary>
	/// 

	private byte CurrentPlayerCheckIndex = 0;

	/// <summary>
	/// A loop flag that indicates the current chunk that is being examined by this ChunkPoint.
	/// </summary>
	/// 

	private int ChunkQueryIndex = 0;

	/// <summary>
	/// When we have finished calculating the chunks that do not collide with other chunks and have them located in SafeChunks.
	/// </summary>

	private bool FinishedCollisionQuery = false;

	/// <summary>
	/// Chunks that can be used without creating conflict with other chunks. (NOTE: This is unreliable until FinishedCollisionQuery is true and will contain unsafe chunks until it is.)
	/// </summary>
	/// 
	private List<PrefabFile> FinalChunkOptions;

	private List<PrefabFile> SafeChunks;

	/// <summary>
	/// Tells us how many times we should query against other chunks in a single frame. Since this process has nested loops that runs traces, it's recommended to have this be a low value.
	/// </summary>

	private static readonly int MaxCollisionQueriesPerFrame = 4;





	protected override void OnStart()
	{
		StageMain = Scene.Directory.FindByName( "Scene Information" ).First().GetComponent<StageMain>();
		ChunkSystem = Scene.Directory.FindByName("ChunkSystem").First().GetComponent<ChunkSystem>();
		ChunkRandom = ChunkSystem.ChunkRandom;

		// Right now, we are just setting SafeChunks to a default value. These chunks may or may not be safe at this point. This list will get narrowed by ChunkCollisionQuery.


		if (!(SpecificChunkList.Length == 0))
		{
			if ( IsWhitelist )
			{
				FinalChunkOptions = new List<PrefabFile>( SpecificChunkList );
			}
			else
			{
				foreach (var item in SpecificChunkList)
				{
					if ( FinalChunkOptions.Contains(item)) {
						FinalChunkOptions.Remove(item);
					}
				}
			}
		}
		else
		{
			FinalChunkOptions = new List<PrefabFile>( StageMain.ChunkPrefabs );
			//StageMain.ChunkPrefabs.ToList<PrefabFile>();
		}

		SafeChunks = new List<PrefabFile>(FinalChunkOptions);
	}


	/// <summary>
	/// Runs a query to find which chunks are compatible with the map in regards to existing chunks and their bounds. This method is designed to be called multiple frames until FinishedCollisionQuery is true.
	/// </summary>

	public void ChunkCollisionQuery()
	{
		var AvailableChunks = FinalChunkOptions;
		var SafeChunksResult = SafeChunks;
		var finalQueryAmount = MaxCollisionQueriesPerFrame;

		if ( (AvailableChunks.Count() - ChunkQueryIndex) < MaxCollisionQueriesPerFrame )
		{
			finalQueryAmount = AvailableChunks.Count() - ChunkQueryIndex;
		}

		var CurrentChunkQueryIndex = ChunkQueryIndex;


		for ( int i = CurrentChunkQueryIndex; i < CurrentChunkQueryIndex + finalQueryAmount; i++ )
		{
			var chunk = AvailableChunks[i];
			var PrefFile = AvailableChunks[i];
			var Scene = PrefFile.GetScene();
			var ChunkPoints = Scene.GetComponentsInChildren<ChunkPoint>();

			var BBounds = ChunkSystem.ChunkBBoxes;
			foreach (var ChunkPoint in ChunkPoints )
			{
				var rot1 = ChunkPoint.WorldRotation.Forward;


				Rotation relativeRotation = Rotation.From(ChunkPoint.WorldRotation.Angles());

				// Apply relative rotation in reference's local space
				var newRot = this.WorldRotation * relativeRotation;

				var RayStruct = new Ray( this.WorldPosition, newRot.Right);

				DebugOverlay.Line( new Line( RayStruct.Position, RayStruct.Project( 10000 )), Color.Blue, 4 );
				var PassedTest = true;
				var HitDistance = 0f;

				foreach ( var Bounds in BBounds)
				{
					DebugOverlay.Box( Bounds, Color.Yellow, 4 );
					var IsHit = Bounds.Trace(RayStruct, 10000, out HitDistance);
					if (IsHit) {
						SafeChunks.RemoveAt(i);
						PassedTest = false;
						break;
					}
				}

				if (!PassedTest)
				{
					break;
				}
			}


			
		}
		ChunkQueryIndex = CurrentChunkQueryIndex + finalQueryAmount;
		if ( AvailableChunks.Count() <= ChunkQueryIndex )
		{
			FinishedCollisionQuery = true;

		}
	}

	/// <summary>
	/// Selects a random safe chunk prefab to be used for chunk generation. The results are then stored in SelectedChunkPrefab.
	/// </summary>
	public void ChooseRandomValidChunk()
	{
		SelectedChunkPrefab = SafeChunks[ChunkSystem.ChunkRandom.Next( 0, SafeChunks.Count())];

	}

	protected override void DrawGizmos()
	{
		Gizmo.Draw.LineThickness = 16f;
		Gizmo.Draw.Color = Color.White.WithAlpha( Gizmo.IsSelected ? 1f : 0.2f );
		Gizmo.Draw.Arrow(Vector3.Zero, new Vector3(0, -86, 0), 32, 12);
		Gizmo.Draw.Color = Gizmo.Colors.Green.WithAlpha( Gizmo.IsSelected ? 1f : 0.2f );
		Gizmo.Draw.SolidBox(new BBox(new Vector3(-32, -32, -32), new Vector3(32, 32, 32)));

		if (Gizmo.IsSelected && Scene.Directory.FindByName( "Model", true ).Count() != 0)
		{
			var Model = Scene.Directory.FindByName( "Model", true ).First().GetComponent<ModelRenderer>();
			Gizmo.Draw.Model(Model.Model, new global::Transform(this.LocalPosition / 2));

		}
	}

	/// <summary>
	/// Checks for the distance against other players. This will then decide if it should ignore it, create a chunk, or delete it's current chunk to make spaces for other chunks overhead.
	/// </summary>
	public void PlayerDistanceCheck()
	{
		var ChunkProcDistanceSq = StageMain.ChunkProcDistance^2;

		if ( StageMain.Players != null && SelectedChunkPrefab != null)
		{
			var Players = StageMain.Players.ToList();
			var Player = Players[CurrentPlayerCheckIndex];

			// If the player is close enough, we generate a chunk
				var PlayerGO = Player.GameObject;
				var Distance = PlayerGO.WorldPosition.DistanceSquared( this.WorldPosition );
				var MyChunk = this.GameObject.Parent.GetComponent<Chunk>();

			// If we have not created a chunk yet.

			if ( GeneratedChunk == null )
			{
				if ( Distance < (ChunkProcDistanceSq * ChunkProcDistanceSq) )
				{
					ChunkSystem.CreateChunk(SelectedChunkPrefab, this);
				}
				if ( CurrentPlayerCheckIndex + 1 < Players.Count )
				{
					CurrentPlayerCheckIndex += 1;
				}
				else
					CurrentPlayerCheckIndex = 0;
			}
		}
	}
	protected override void OnUpdate()
	{
		if (GeneratedChunk == null)
		{
			if ( ChunkProcUpdateTick.ElapsedSeconds > 0.1 )
			{
				PlayerDistanceCheck();
				ChunkProcUpdateTick = FastTimer.StartNew();
			}
		}


		if (!FinishedCollisionQuery)
		{
			ChunkCollisionQuery();
		}

		else if (SelectedChunkPrefab == null)
		{
			ChooseRandomValidChunk();
		}
	}
}
